<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4SrNhSo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4SrNhSo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4SrNhSo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4SrNhSo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4SrNhSo\App_KernelDevDebugContainer([
    'container.build_hash' => '4SrNhSo',
    'container.build_id' => '93c76a94',
    'container.build_time' => 1607289673,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4SrNhSo');
